server:
  port: 8090

spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/coredb
    username: core
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: sp
#        show_sql: true
#        use_sql_comments: true
    #        format_sql: true
  liquibase:
    change-log: changelog/db.master-develop-data-changelog.yaml
    enabled: true

springdoc:
  api-docs:
    enabled: true
    path: api-docs
  swagger-ui:
    enabled: true
    path: swagger-ui

logging:
  level:
    root: info
    org.springframework: info
    sgm.test: DEBUG

